### ISSUE TITLE
SECURITY.py file is not opening 

### ISSUE THREAD

**Issue by ibranraeen** [roshan9419/PersonalAssistantChatbot#5]
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (1022) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (376) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -2147023170
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (388) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873851
[ WARN:1] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Please help to solve the problem.**

**Comment by roshan9419** [comment]
Looks like it is just a warning. Does the file is not even opening, or is getting failed at some step?

Could you please tell me what python version you're using and have you installed these libraries?
`pip install opencv-contrib-python`
`pip install opencv`

**Comment by ibranraeen** [comment]
When i install and setup in October 2021 its properly working capture face do all task perfectly but when i open security.py on march 2022 it is not opening face cam not opening its show some error in opencv.

**Comment by roshan9419** [comment]
You'll see a `userData` folder created when you had registered, please try to delete this folder and try again, because it contains facial data and other settings.

**Comment by ibranraeen** [comment]
**after deleting user data file i still got error**
`[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\videoio\src\cap_msmf.cpp (1022) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\ibran raeen\Desktop\PersonalAssistantChatbot-main\SECURITY.py", line 134, in Add_Face
    startCapturing()
  File "C:\Users\ibran raeen\Desktop\PersonalAssistantChatbot-main\SECURITY.py", line 93, in startCapturing
    if face_extractor(frame) is not None:
  File "C:\Users\ibran raeen\Desktop\PersonalAssistantChatbot-main\SECURITY.py", line 77, in face_extractor
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)`
`cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

**my Python version is 3.7.8
windows 11**

**Comment by roshan9419** [comment]
According to this, you're getting errors while adding your face, right?
Is something wrong with the camera or some settings which are blocking `CV2` to capture the frame. The `frame` value which is passed in the `face_extractor(frame)` function is None, which is causing the error.

**Comment by ibranraeen** [comment]
So what is the solution?

**Comment by harshb2486** [comment]
ibran can we talk a little i have wrote u mail and send u request on insta too.....
