### ISSUE TITLE
security.py is opening but its showing face locked

### ISSUE THREAD

**Issue by moksha225** [roshan9419/PersonalAssistantChatbot#7]
![Screenshot (30)](https://user-images.githubusercontent.com/70622351/164264138-d0dac38b-4c2a-4154-8b4d-e36a7a5af606.png)
![Screenshot (29)](https://user-images.githubusercontent.com/70622351/164264177-046e0588-e135-4294-99b6-1099890c6cce.png)

**Comment by roshan9419** [comment]
I have mistakenly added unwanted folders in git like **userData, Downloads, Files and Document**, which is not necessary.
I have removed this now. You can pull the latest changes or want to download then just download again.

**Comment by moksha225** [comment]
after downloading new version there is some error
[ WARN:0@36.987] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\MOKSHA\Dropbox\PC\Desktop\PersonalAssistantChatbot-master\SECURITY.py", line 69, in trainFace
    model = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2' has no attribute 'face'

**Comment by roshan9419** [comment]
have you installed the OpenCV as mentioned in Readme? Try to uninstall and install it and try to install both mentioned opencv packages, also try with opencv-contrib-python.
Which python version you're using in your system?

**Comment by moksha225** [comment]
I installed open cv
And i am using 3.7 python version
